import { StyleSheet } from 'react-native';

export const materialsStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f9fafb' },
    header: { paddingHorizontal: 16, paddingVertical: 16, backgroundColor: 'white', borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
    headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
    headerTitle: { fontSize: 24, fontWeight: 'bold', color: '#111827' },
    headerSubtitle: { fontSize: 12, color: '#6b7280' },
    addButton: { backgroundColor: '#b94a48', padding: 12, borderRadius: 12 },
    tabContainer: { flexDirection: 'row', backgroundColor: '#f3f4f6', padding: 4, borderRadius: 12 },
    tab: { flex: 1, paddingVertical: 8, borderRadius: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
    tabActive: { backgroundColor: 'white', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2, elevation: 2 },
    tabText: { fontWeight: '500', color: '#6b7280' },
    tabTextActive: { color: '#b94a48' },
    loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', opacity: 0.5, gap: 16 },
    emptyStateText: { color: '#9ca3af', textAlign: 'center', paddingHorizontal: 32 },
    listHeaderText: { color: '#6b7280', fontSize: 14, marginBottom: 12 },
    orderCard: { backgroundColor: 'white', padding: 16, borderRadius: 12, borderWidth: 1, borderColor: '#f3f4f6', marginBottom: 12 },
    orderCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 },
    orderDateRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    orderDate: { color: '#6b7280', fontSize: 14 },
    orderItemCount: { fontWeight: 'bold', color: '#111827', fontSize: 18, marginTop: 4 },
    orderItemsPreview: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginBottom: 8 },
    itemTag: { backgroundColor: '#f3f4f6', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4 },
    itemTagText: { fontSize: 12, color: '#4b5563' },
    orderTotalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 8, borderTopWidth: 1, borderTopColor: '#f3f4f6' },
    orderTotalLabel: { color: '#6b7280', fontSize: 14 },
    orderTotalValue: { fontWeight: 'bold', color: '#b94a48', fontSize: 18 },
    completedRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 8, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#f3f4f6' },
    completedText: { color: '#10b981', fontSize: 12 },
    editingBanner: { paddingHorizontal: 16, paddingVertical: 8, backgroundColor: '#fef2f2', borderBottomWidth: 1, borderBottomColor: '#fecaca' },
    editingBannerText: { color: '#7f1d1d', fontWeight: '500', textAlign: 'center' },
    itemCard: { backgroundColor: 'white', padding: 16, borderRadius: 12, borderWidth: 1, borderColor: '#f3f4f6', marginBottom: 12 },
    itemCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 },
    itemName: { fontWeight: 'bold', color: '#111827', fontSize: 18 },
    supplierRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
    supplierText: { color: '#6b7280', fontSize: 14 },
    itemDetailsRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f9fafb', borderRadius: 8, padding: 8, gap: 16 },
    itemDetail: { alignItems: 'center' },
    itemDetailLabel: { fontSize: 12, color: '#6b7280' },
    itemDetailValue: { fontWeight: '600', color: '#111827' },
    itemTotal: { fontWeight: 'bold', color: '#b94a48', fontSize: 16 },
    footer: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: 'white', borderTopWidth: 1, borderTopColor: '#f3f4f6' },
    footerTotalRow: { padding: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#f9fafb' },
    footerTotalLabel: { color: '#6b7280', fontWeight: '500' },
    footerTotalValue: { fontSize: 24, fontWeight: 'bold', color: '#111827' },
    footerButtons: { padding: 16, flexDirection: 'row', gap: 12 },
    footerButtonSecondary: { flex: 1, backgroundColor: '#f3f4f6', borderRadius: 12, padding: 12, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 },
    footerButtonSecondaryText: { color: '#374151', fontWeight: '500' },
    footerButtonTeal: { flex: 1, backgroundColor: '#b94a48', borderRadius: 12, padding: 12, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 },
    footerButtonBlue: { flex: 1, backgroundColor: '#2563eb', borderRadius: 12, padding: 12, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 },
    footerButtonText: { color: 'white', fontWeight: '500' },
    modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.5)' },
    modalContent: { backgroundColor: 'white', borderTopLeftRadius: 24, borderTopRightRadius: 24, height: '85%' },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
    modalTitle: { fontSize: 20, fontWeight: 'bold', color: '#111827' },
    modalCloseButton: { backgroundColor: '#f3f4f6', padding: 8, borderRadius: 999 },
    inputLabel: { fontSize: 14, fontWeight: '600', color: '#374151', marginBottom: 8 },
    input: { backgroundColor: '#f9fafb', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 12, padding: 12, fontSize: 16, marginBottom: 16 },
    inputRow: { flexDirection: 'row', marginBottom: 16 },
    totalPreview: { backgroundColor: '#eff6ff', padding: 12, borderRadius: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: '#dbeafe', marginBottom: 16 },
    totalPreviewLabel: { color: '#1d4ed8', fontWeight: '500' },
    totalPreviewValue: { color: '#1e40af', fontWeight: 'bold', fontSize: 18 },
    addItemButton: { backgroundColor: '#b94a48', padding: 16, borderRadius: 12, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, marginBottom: 32 },
    addItemButtonText: { color: 'white', fontWeight: 'bold', fontSize: 18 },
    confirmButton: { backgroundColor: '#16a34a', padding: 16, borderRadius: 12, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, marginBottom: 12 },
    confirmButtonText: { color: 'white', fontWeight: 'bold', fontSize: 18 },
    cancelButton: { padding: 16, borderRadius: 12, backgroundColor: '#f3f4f6', alignItems: 'center', marginTop: 16, marginBottom: 32 },
    cancelButtonText: { color: '#374151', fontWeight: '500' },
    detailSection: { backgroundColor: '#f9fafb', padding: 16, borderRadius: 12, marginBottom: 16 },
    detailRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
    detailLabel: { color: '#6b7280', fontSize: 14 },
    detailValue: { color: '#111827', fontSize: 16 },
    sectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#111827', marginBottom: 12 },
    detailItemCard: { backgroundColor: 'white', padding: 12, borderRadius: 12, borderWidth: 1, borderColor: '#e5e7eb', marginBottom: 12 },
    detailItemName: { fontWeight: 'bold', color: '#111827', fontSize: 16, marginBottom: 8 },
    detailItemRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
    detailItemInfo: { alignItems: 'center' },
    detailItemLabel: { fontSize: 12, color: '#6b7280' },
    detailItemValue: { fontSize: 14, color: '#111827' },
    recreateButton: { padding: 16, borderRadius: 12, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 },
    recreateButtonText: { color: 'white', fontWeight: '600', fontSize: 16 },
    invoiceButton: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#f3f4f6', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8 },
    invoiceButtonAttached: { backgroundColor: '#ecfdf5', borderWidth: 1, borderColor: '#a7f3d0' },
    invoiceButtonText: { color: '#374151', fontSize: 13, fontWeight: '500' },
    invoiceButtonTextAttached: { color: '#059669' },
    invoiceSection: { backgroundColor: '#f9fafb', borderRadius: 12, padding: 16, marginBottom: 16 },
    invoiceSectionTitle: { fontSize: 16, fontWeight: 'bold', color: '#111827', marginBottom: 12, flexDirection: 'row', alignItems: 'center' },
    invoiceImage: { width: '100%', height: 200, borderRadius: 8, marginBottom: 8 },
    invoiceOpenButton: { backgroundColor: '#2563eb', padding: 12, borderRadius: 10, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 },
    invoiceOpenButtonText: { color: 'white', fontWeight: '500', fontSize: 14 },
});
