export { PatientCard } from './PatientCard';
export { PatientForm } from './PatientForm';
export { PatientSearch } from './PatientSearch';
export { DocumentUpload } from './DocumentUpload';
export { NewPatientDialog } from './NewPatientDialog';
export { EditPatientDialog } from './EditPatientDialog';
export { PatientHeader } from './PatientHeader';
export { AppointmentsTab } from './AppointmentsTab';
export { ProceduresTab } from './ProceduresTab';
export { PaymentsTab } from './PaymentsTab';
export { PatientInfoTab } from './PatientInfoTab';
export { NewProcedureDialog } from './NewProcedureDialog';
export { ExamsTab } from './ExamsTab';
export { NewExamDialog } from './NewExamDialog';
export { AnamneseTab } from './AnamneseTab';
export { AnamneseSummaryDialog } from './AnamneseSummaryDialog';
export { BudgetsTab } from './BudgetsTab';
export { PatientAiConsent } from './PatientAiConsent';

